### ISSUE TITLE
When will AsyncFile based on io_uring be supported?

### ISSUE THREAD

**Issue by dreamlike-ocean** [vert-x3/vertx-io_uring-incubator#7]
#### Describe the feature

It would be great if we could implement the async file driven by io_uring within this module.

https://github.com/netty/netty-incubator-transport-io_uring/issues/210

#### Use cases

 Using the same set of event loop mechanisms to support efficient file I/O.

#### Contribution

If you think this suggestion is good, I can try to contribute an implementation.
Just like
 https://github.com/dreamlike-ocean/netty/blob/feature-asyncfile/transport-classes-io_uring/src/main/java/io/netty/channel/uring/IoUringAsyncFile.java

**Comment by vietj** [comment]
This implementation should be done in Vert.x 5, note that vertx 5 is not based anymore on incubator but instead on Netty 4.2 io_uring implementation.

We would welcome such implementation in Vert.x 5 of course.

**Comment by dreamlike-ocean** [comment]
> This implementation should be done in Vert.x 5, note that vertx 5 is not based anymore on incubator but instead on Netty 4.2 io_uring implementation.
> 
> We would welcome such implementation in Vert.x 5 of course.

Got it. I will try to contribute an implementation after the release of version 4.2.
